apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: lobechat
data:
  agent.json: |
    {
      "enableFileUpload": true,
      "enableTextFileUpload": true,
      "enableImageUpload": true,
      "maxFileSize": 10485760,
      "allowedFileTypes": ["txt", "md", "json", "pdf", "png", "jpg", "jpeg"],
      "database": {
        "type": "postgres",
        "url": "postgresql://lobechat:lobechat123@postgres:5432/lobechat"
      }
    }
