apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lobechat-storage
  namespace: lobechat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
